# Example OlmOCR Training Configuration

# Project metadata
project_name: olmocr-qwen-vl-training
run_name: qwen2.5-vl-7b-finetune

# Model configuration
model:
  name: Qwen/Qwen2.5-VL-7B-Instruct
  trust_remote_code: true
  torch_dtype: auto
  use_flash_attention: true
  attn_implementation: flash_attention_2
  
  # LoRA settings (disabled by default)
  use_lora: false
  lora_rank: 8
  lora_alpha: 32
  lora_dropout: 0.1
  lora_target_modules:
    - q_proj
    - v_proj
    - k_proj
    - o_proj

# Dataset configuration
dataset:

  train:
    - root_dir: /home/ubuntu/olmOCR-mix-0225/processed_00_documents_train_s2pdf/
      pipeline *basic_pipeline:
        - name: FrontMatterParser
          front_matter_class: PageResponse
        - name: PDFRenderer
          target_longest_image_dim: 1024
        - name: StaticLengthDocumentAnchoring
          target_anchor_text_len: 1000
        - name: FinetuningPrompt
        - name: FrontMatterOutputFormat
        - name: InstructUserMessages
        - name: Tokenizer
          masking_index: -100
          end_of_message_token: "<|im_end|>"
    - root_dir: /home/ubuntu/olmOCR-mix-0225/processed_00_books_train_s2pdf/
      pipeline: *reuse basic_pipeline above*

  eval:
    - root_dir: /home/ubuntu/olmOCR-mix-0225/processed_00_documents_eval_s2pdf/
      pipeline: *reuse basic_pipeline above*
    - root_dir: /home/ubuntu/olmOCR-mix-0225/processed_00_books_eval_s2pdf/
      pipeline: *reuse basic_pipeline above*



# Training configuration
training:
  output_dir: ./outputs/qwen2.5-vl-olmocr
  num_train_epochs: 3
  
  # Batch size and accumulation
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 8
  
  # Learning rate
  learning_rate: 2e-5
  lr_scheduler_type: cosine
  warmup_ratio: 0.1
  
  # Optimization
  optim: adamw_torch
  weight_decay: 0.01
  max_grad_norm: 1.0
  
  
  # Evaluation and checkpointing
  evaluation_strategy: steps
  eval_steps: 500
  save_strategy: steps
  save_steps: 500
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: eval_loss
  greater_is_better: false
  
 