name: Build and Push Docker Image
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
      - '*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.0.0) - leave empty for dev build'
        required: false
        type: string

env:
  REGISTRY: docker.io
  IMAGE_NAME: alleninstituteforai/olmocr

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet \
            /usr/local/lib/android \
            /opt/ghc \
            /opt/hostedtoolcache/CodeQL
          sudo docker system prune -af
          sudo apt-get -y autoremove
          sudo apt-get -y autoclean
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Calculate version tags
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]] && [[ -n "${{ github.event.inputs.version }}" ]]; then
            VERSION="${{ github.event.inputs.version }}"
            VERSION="${VERSION#v}"  # Remove v prefix if present
            
            # Split version into parts
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
            
            # Generate tags
            echo "tags<<EOF" >> $GITHUB_OUTPUT
            echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}" >> $GITHUB_OUTPUT
            echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${MAJOR}.${MINOR}" >> $GITHUB_OUTPUT
            echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${MAJOR}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
          fi

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=dev-{{date 'YYYYMMDD'}}-{{sha}},enable=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version == '' }}
          flavor: |
            latest=false

      - name: Override tags for manual version
        id: tags
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]] && [[ -n "${{ github.event.inputs.version }}" ]]; then
            echo "tags=${{ steps.version.outputs.tags }}" >> $GITHUB_OUTPUT
          else
            echo "tags=${{ steps.meta.outputs.tags }}" >> $GITHUB_OUTPUT
          fi

      - name: Debug metadata
        run: |
          echo "Final Tags: ${{ steps.tags.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"
          echo "Version: ${{ steps.version.outputs.version || steps.meta.outputs.version }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          outputs: type=registry
          no-cache: true

      - name: Clean up after build
        if: always()
        run: |
          docker system prune -af --volumes
          df -h