name: Build and Push Docker Image

on:
  # ① Run when a release is published …
  release:
    types: [published]

  # ② … or when a SemVer-style tag is pushed (with or without “v” prefix)
  push:
    tags:
      - 'v*'      # v1.2.3
      - '*.*.*'   # 1.2.3

  # ③ Manual trigger (optional)
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: alleninstituteforai/olmocr

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---------------------------------------------
      # Tag & label generation – never create :latest
      # ---------------------------------------------
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false                         # ban implicit :latest
          tags: |
            # Tags coming from a pushed Git tag
            type=ref,event=tag

            # Release event → use the release tag name
            type=raw,value=${{ github.event.release.tag_name }},enable=${{ github.event_name == 'release' }}
            type=semver,pattern={{version}},enable=${{ github.event_name == 'release' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name == 'release' }}
            type=semver,pattern={{major}},enable=${{ github.event_name == 'release' }}

      # Fail fast if no tags were produced
      - name: Abort when tag list is empty
        if: ${{ steps.meta.outputs.tags == '' }}
        run: |
          echo "::error ::No Docker tags were generated for this event. Did you trigger the workflow without a Git tag or Release tag?"
          exit 1

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          outputs: type=registry
          no-cache: true